# Generated by Django 5.1.7 on 2025-03-17 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbrirSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_solicitante', models.CharField(blank=True, max_length=80, null=True)),
                ('info', models.CharField(max_length=200)),
                ('data_solici', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
