# Generated by Django 5.1.7 on 2025-03-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrirsolicitacao',
            name='info',
            field=models.CharField(max_length=400, verbose_name='Informações'),
        ),
        migrations.AlterField(
            model_name='abrirsolicitacao',
            name='nome_solicitante',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome do solicitante '),
        ),
    ]
