# Generated by Django 5.1.7 on 2025-03-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_abrirsolicitacao_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrirsolicitacao',
            name='prioridade',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta'), ('Urgente', 'Urgente'), ('Imediata', 'Imediata')], default='Baixa', max_length=20, verbose_name='Prioridade'),
        ),
    ]
